# Generated by Django 4.2.27 on 2026-02-06 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SandboxToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sandbox Token',
                'verbose_name_plural': 'Sandbox Tokens',
                'db_table': 'sandbox_tokens',
            },
        ),
        migrations.CreateModel(
            name='PANVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_number', models.CharField(max_length=10)),
                ('full_name_match', models.BooleanField(default=False)),
                ('dob_match', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=20)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pan_verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PAN Verification',
                'verbose_name_plural': 'PAN Verifications',
                'db_table': 'pan_verifications',
            },
        ),
    ]
