# Generated by Django 4.2.27 on 2026-02-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox_integration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panverification',
            name='pan_number',
        ),
        migrations.AddField(
            model_name='panverification',
            name='verified_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='panverification',
            name='verified_full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
