# Generated by Django 6.0.1 on 2026-02-25 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultant_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='consultantdocument',
            table='consultant_documents_consultantdocument',
        ),
    ]
