# Generated by Django 6.0.2 on 2026-02-25 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'db_table': 'assessment_testtype',
            },
        ),
        migrations.CreateModel(
            name='FaceVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_image_path', models.CharField(max_length=255)),
                ('live_image_path', models.CharField(blank=True, default='', max_length=255)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('is_match', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'face_verifications',
                'ordering': ['-verified_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_domains', models.JSONField(default=list)),
                ('question_set', models.JSONField(default=list)),
                ('video_question_set', models.JSONField(default=list)),
                ('score', models.FloatField(default=0.0)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('flagged', 'Flagged')], default='ongoing', max_length=20)),
                ('violation_count', models.IntegerField(default=0)),
                ('test_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultant_assessment.testtype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assessment_usersession',
            },
        ),
        migrations.CreateModel(
            name='ProctoringSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_violation', models.BooleanField(default=False)),
                ('violation_reason', models.TextField(blank=True, null=True)),
                ('face_count', models.IntegerField(default=0)),
                ('match_score', models.FloatField(default=0.0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_snapshots', to='consultant_assessment.usersession')),
            ],
            options={
                'db_table': 'assessment_proctoringsnapshot',
            },
        ),
        migrations.CreateModel(
            name='VideoQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('test_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_questions', to='consultant_assessment.testtype')),
            ],
            options={
                'db_table': 'assessment_videoquestion',
            },
        ),
        migrations.CreateModel(
            name='VideoResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_identifier', models.CharField(default='unknown', max_length=255)),
                ('video_file', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ai_transcript', models.TextField(blank=True, null=True)),
                ('ai_score', models.IntegerField(blank=True, null=True)),
                ('ai_feedback', models.JSONField(blank=True, null=True)),
                ('ai_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_responses', to='consultant_assessment.usersession')),
            ],
            options={
                'db_table': 'assessment_videoresponse',
            },
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='consultant_assessment.usersession')),
            ],
            options={
                'db_table': 'assessment_violation',
            },
        ),
    ]
